### ISSUE TITLE
6-DoF IMU

### ISSUE THREAD

**Issue by ks32** [yahyatawil/qiblah#1]
Very interesting project. Can you confirm if it can work with 6 way 6-DoF IMU?

**Comment by yahyatawil** [comment]
All the technical details are found in the documentation here: 
https://atadiat.com/en/e-open-source-qibla-compass-with-tilt-compensation/ 

It is using 9-DoF but it can work with 6 DoF.

**Comment by ks32** [comment]
is it only working with Magnetometer? can it work with only using 6 way gyro and GPS (no Magnetometer)?

**Comment by yahyatawil** [comment]
The arduino code will need a modification for sure, as the direction is gotten from Magnetometer. Howerver, the tilt compensation will work either the direction is from Magnetometer or from GPS. However, I don't know if the direction from GPS requires a tilt compensation in the first place or not.
